---
  - name: "Configure MariaDB repo"
    copy:
      content: |
        # MariaDB 10.1 CentOS repository list
        # http://downloads.mariadb.org/mariadb/repositories/
        [mariadb]
        name = MariaDB
        baseurl = http://yum.mariadb.org/10.1/centos7-amd64
        gpgkey=https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
        gpgcheck=1
      dest: /etc/yum.d/mariaDB

  - name: "Install MariaDB and dependencies"
    package:
      name: "{{item}}"
    with_items:
      - MariaDB-server
      - MariaDB-client
      - MySQL-python

  - systemd:
      name: mariadb
      state: started

  - name: Create database replication user
    mysql_user:
      name: "repl"
      password: "cwnyb3uy23grdsx"
      priv: "*.*:REPLICATION SLAVE,REPLICATION CLIENT"
      host: "10.%"
      state: present

  #- name: "Configure mariaDB Server"
  #  template:
  #    dest: "/etc/my.cnf.d/server.cnf"
  #    src: "server.cnf.j2"
  #  tags: config
  #  notify: restart mariadb

  - name: Configure Logrotate
    copy:
      dest: /etc/logrotate.d/mysql-server
      src: logrotate.conf
