---
  - name: "Configure MariaDB repo"
    yum_repository:
      name: "mariaDB"
      baseurl: "http://yum.mariadb.org/10.1/rhel7-amd64"
      gpgkey:  "https://yum.mariadb.org/RPM-GPG-KEY-MariaDB"
      description: "MariaDB 10.x"

  - name: "Install MariaDB and dependencies"
    package:
      name: "{{item}}"
    with_items:
      - MariaDB-server
      - MariaDB-client
      - MySQL-python

  - name: Create database replication user
    mysql_user:
      name: "repl"
      password: "cwnyb3uy23grdsx"
      priv: "*.*:REPLICATION CLIENT"
      state: present

  - name: "Configure mariaDB Server"
    template:
      dest: "/etc/my.cnf.d/server.cnf"
      src: "server.cnf.j2"
    tags: config
    notify: restart mariadb
