- systemd:
    name: mariadb
    state: restarted

- mysql_replication:
    mode: getslave
  register: slave

- debug: msg="{{slave}}"

- mysql_replication:
    mode: getmaster
  register: master
  tags: repl

- debug: msg="{{master}}"
  tags: repl

- name: "DEBUG MASTER"
  debug:
    msg: "{{hostvars[item]['master']}}"
  with_items:  "{{groups['tag_role_db']}}"

- set_fact:
    master_bin_file: "{{hostvars[item].master.File}}"
  with_items:  "{{groups['tag_role_db']}}"
  when: hostvars.item is defined and ansible_ec2_local_ipv4 != item
  tags: repl

- set_fact:
    master_bin_pos: "{{hostvars[item].master.Position}}"
  with_items:  "{{groups['tag_role_db']}}"
  when: ansible_ec2_local_ipv4 != item
  tags: repl

- set_fact:
    master_host: "{{item}}"
  with_items:  "{{groups['tag_role_db']}}"
  when: ansible_ec2_local_ipv4 != item
  tags: repl

- debug: msg="{{master_host}} {{master_bin_file}} {{master_bin_pos}}"
  tags: repl

- mysql_replication:
    mode: stopslave
  ignore_errors: true
  when: slave.Is_Slave == false or slave.Slave_IO_Running != "Yes"
  tags: repl

- mysql_replication:
    mode: changemaster
    master_host: "{{master_host}}"
    master_log_file: "{{master_bin_file}}"
    master_log_pos: "{{master_bin_pos}}"
    master_user: "repl"
    master_password: "cwnyb3uy23grdsx"

  when: slave.Is_Slave == false or slave.Slave_IO_Running != "Yes"
  tags: repl

- mysql_replication:
    mode: startslave
  when: slave.Is_Slave == false or slave.Slave_IO_Running != "Yes"
  tags: repl
